### ISSUE TITLE
How to get .npy files?

### ISSUE THREAD

**Issue by hcmdgh** [XuhuiZhou/CDA#2]
In the section Running BERT-HAN -> Running experiments on our corpora, when I tried to run get_rep.py, I don't know what the TEST_FILE is. I have tried test_cite.txt, test_cite.index and test_cite.csv in your provided dataset AAN, but none of them worked. So which file to use? Thanks a lot.

**Comment by XuhuiZhou** [comment]
Hi, the txt file should work. Could you show me the error you get?

**Comment by hcmdgh** [comment]
When I try to run get_rep.py with these parameters:

> --output_dir=cite_models
> --overwrite_output_dir
> --model_type=bert
> --per_gpu_eval_batch_size=10
> --model_name_or_path=bert-large-cased
> --line_by_line
> --train_data_file=haha
> --special_eval
> --eval_data_file=somepath\数据集\MDA\AAN\test_cite.txt
> --rep_name=./my.npy
> --mlm

I got a mistake like this:
```
Traceback (most recent call last):
  File "somepath/CDA/get_rep.py", line 846, in <module>
    main()
  File "somepath/CDA/get_rep.py", line 823, in main
    results = evaluate(args, model, tokenizer)
  File "somepath/CDA/get_rep.py", line 457, in evaluate
    eval_dataset = load_and_cache_examples(args, tokenizer, evaluate=True)
  File "somepath/CDA/get_rep.py", line 186, in load_and_cache_examples
    return LineByLineTextDataset(tokenizer, args, file_path=file_path, block_size=args.block_size)
  File "somepath/CDA/get_rep.py", line 164, in __init__
    label = int(row[-1].strip()) 
ValueError: invalid literal for int() with base 10: 'focusing on the paraphras- ing of japanese light-verb constructions (lvcs).'
```

What's wrong with that?
And when using your copora, I don't find any .npy file in your provided dataset 😂

**Comment by XuhuiZhou** [comment]
Thanks for pointing that out.

Fixed the bug. Please try again.

The idea of `get_rep.py` is to obtain sentence vectors from pre-trained embedding. So the input should be the per-sentence `.txt` file.  

`get_rep` is adapted from HF's LM finetuning script, which might help by taking a look at their original script too.

**Comment by adityavadalkar** [comment]
Hey, I am trying to generate the npy files but the get_rep.py file generates just one .npy file. But the acl_train_bert.sh file requires train_cite.npy as well as dev_cite.npy. This may be a stupid question but can you please instruct me on what to do next? Or please just tell me the config you used to run the get_rep script.

**Comment by XuhuiZhou** [comment]
Hi, you just need to run the script for both train and dev sets :)
